from aiogram.dispatcher.filters.state import StatesGroup, State


class Calc(StatesGroup):
    ScoreCounter = State()
    FirstGroup = State()
    SecondGroup = State()
    ThirdGroup = State()
    FourthGroup = State()
    FifthGroup = State()
    Force = State()
    PullUp = State()
    RiseWithForce = State()
    RiseWithCoup = State()
    VPN = State()
    Arb = State()
    speed = State()
    speed_60m = State()
    speed_100m = State()
    speed_10x10 = State()
    speed_second = State()
    endurance = State()
    endurance_1000 = State()
    endurance_1000_2 = State()
    endurance_1000_3 = State()
    endurance_1000_4 = State()
    endurance_3000 = State()
    endurance_3000_2 = State()
    endurance_3000_3 = State()
    endurance_5000 = State()
    endurance_5000_2 = State()
    endurance_5000_3 = State()
    endurance_5000_4 = State()
